language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build

before_install:
  - python --version
  - python -m pip install --upgrade pip
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

# Command to install dependencies
install:
  - easy_install distribute
  - pip install -r build/requirements.txt
  
# Command to run tests
script:
  - python3 src/picktool.py